### ISSUE TITLE
Ensemble.save() does not save forces, energies and stresses

### ISSUE THREAD

**Issue by DjordjeDangic** [SSCHAcode/python-sscha#126]
If we are using the compute_ensemble() function to calculate forces, energies, and stresses and afterward use ensemble.save() function, it does not save forces, stresses, or energies because ensemble.force_computed is False. This should be updated in the compute_ensemble() function I guess. Also, maybe I nice functionality would be to pass a number of configurations variable in the ensemble.load_bin() function like it is in the ensemble.load() function. I find it useful when converging calculations.

**Comment by diegomartinez2** [comment]
I'm looking at the "ensemble.force_computed is False" problem. By using 'compute_ensemble()' I think the "force_computed" is changed when the 'get_energy_force()' is called but when using the cluster the function 'cluster.compute_ensemble()' is called that do not have "force_computed" flags.

**Comment by mesonepigreco** [comment]
Ok then definitively this is a bug (luckily an easy one to fix).
Right now to converge we can use the split and merge function of the ensemble. However, I do understand that they are quite non intuitive to do something as simple as limit the number of configurations. I agree with Diego that introducing N in the load_bin is not the best thing, as it could be easy to specify the wrong number by mistake and accidentally use less configurations, especially because the code needs anyway to load all the configurations in the binary format (unlike with the standard file format that the extra configurations are not loaded at all).

If you agree, we can add a simpler function, something like reduce_to(N_cfgs : int) to remove from the ensemble the extra configurations and do the convergence test in an easier way.

**Comment by DjordjeDangic** [comment]
Great! Glad it's resolved!
